// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbrepo

import (
	"time"
)

// 用户表
type User struct {
	// 主键
	ID uint64 `json:"id"`
	// 用户邮箱
	Email string `json:"email"`
	// 哈希密码
	PasswordHash string `json:"password_hash"`
	// 用户名称
	Username string `json:"username"`
	// 用户头像
	Avatar string `json:"avatar"`
	// 角色;0:客户,1:管理员
	Role bool `json:"role"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
}
