version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${WEB_PORT}:9400"
    volumes:
      - .:/usr/src/app
    command: air main.go -b 0.0.0.0

  mysqldb:
    image: "mysql:5.7.22"
    ports:
      # mysql端口映射，属主机使用这个mysql服务，用DB_PORT端口；而容器之间使用则用 3306
      - "${DB_PORT}:3306"  
    restart: always  # 总是启动，当docker启动时，就会启动这个服务
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${DB_STORAGE}:/var/lib/mysql
    networks:
      - default