version: '3.9'

services:
  web:
    container_name: ebook_web
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${WEB_PORT}:9400"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql
      # - rabbitmq
      # - minio
    command: air cmd/web/*.go -b 0.0.0.0

  mysql:
    image: "mysql:5.7.22"
    container_name: ebook_mysql
    ports:
      - "3308:3306"
    # restart: always # 总是启动，当docker启动时，就会启动这个服务
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${DB_STORAGE}:/var/lib/mysql
    networks:
      - default

  minio:
    image: quay.io/minio/minio
    container_name: ebook_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_USER_PASSWORD}
    volumes:
      - ${MINIO_STORAGE}:/data
    command: server /data --console-address ":9001"

  rabbitmq:
    image: 'rabbitmq:4.0.2-management-alpine'
    container_name: ebook_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ${RABBITMQ_STORAGE}:/var/lib/rabbitmq